# Generated by Django 4.2.5 on 2023-09-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lumber',
            fields=[
                ('ref_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.lumber')),
            ],
        ),
    ]
