# Generated by Django 4.2.5 on 2023-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_length_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='a4A04K', max_length=12, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
