# Generated by Django 4.2.5 on 2023-09-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='length',
            old_name='ref_id',
            new_name='lumber',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='dPIPFN', max_length=12, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='length',
            unique_together={('lumber', 'length')},
        ),
    ]
