# Generated by Django 4.2.5 on 2023-09-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_lumber_lumber_type_alter_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='Xzi9wW', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='lumber_type',
            field=models.CharField(choices=[('lvl', 'Versa-Lam Beam'), ('knottypine', '#2 White Pine'), ('clearpine', 'Clear White Pine'), ('poplar', 'Poplar'), ('knottycedar', 'Knotty Cedar'), ('clearcedar', 'Clear Cedar')], default=None, max_length=30, null=True),
        ),
    ]
