# Generated by Django 4.2.5 on 2023-09-25 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_alter_invitation_code_alter_lumber_lumber_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumber',
            name='user',
            field=models.ForeignKey(default=inventory.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='Od8Vmv', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='lumber_type',
            field=models.CharField(choices=[('lvl', 'Versa-Lam Beam'), ('knottypine', '#2 White Pine')], default=None, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sales_code', models.CharField(default=django.utils.crypto.get_random_string, max_length=6, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('salesorder', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.length')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.lumber')),
                ('user', models.ForeignKey(default=inventory.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('change_code', models.CharField(default=django.utils.crypto.get_random_string, max_length=6, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('changetype', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment')], max_length=10)),
                ('user', models.ForeignKey(default=inventory.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
