# Generated by Django 4.2.5 on 2023-09-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_lumber_user_alter_invitation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='changetype',
            field=models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment')], default='adjustment', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='BlUvVd', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_code',
            field=models.CharField(default='C9aXO8', max_length=6, primary_key=True, serialize=False),
        ),
    ]
