# Generated by Django 4.2.5 on 2023-09-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_changelog_change_code_alter_invitation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='FZADlb', max_length=12, unique=True),
        ),
    ]
