# Generated by Django 4.2.5 on 2023-09-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='gSMqcM', max_length=12, unique=True),
        ),
    ]
