# Generated by Django 4.2.5 on 2023-09-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_changelog_description_alter_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='nvxsN9', max_length=12, unique=True),
        ),
    ]
